#! /bin/sh
#
# very simple minded startup script for CollabKit
# created by Christian Beier <dontmind@freeshell.org>


# possible speedups:
# -noxdamage, -deferupdate 0, -input_skip <n>, -pointer_mode [1 or 4]
# -ncache <n>
# -nofb
# -threads
MXVNC_OPTS="-mcast -speeds lan -nowait_bog -pointer_mode 4 -threads -afteraccept setcursor_helper -extra_fbur 10 -setdefer 2 -nonap"
VIEWER_OPTS="-appshare -acceptpopup -viewonly -quality 7 -compresslevel 5"

    
#######################################################################

PATH=/usr/lib/collabkit:./bin:$PATH


ANNOTATE_PIDFILE=/tmp/CK-annotate.pid
VNCSERV_PIDFILE=/tmp/CK-vncserv.pid
VNCVIEW_PIDFILE=/tmp/CK-vncview.pid

#set -e

trap "{ stop; exit 1; }" INT QUIT

start()
{
        # first, start annotation app
	gromit-mpx &
	echo $! > $ANNOTATE_PIDFILE
        # then, the VNC server MXVNC
	mxvnc $MXVNC_OPTS &
	echo $! > $VNCSERV_PIDFILE
	# third, the vnc viewer to receive incoming windows
	vncviewer $VIEWER_OPTS &
	echo $! > $VNCVIEW_PIDFILE
}


stop()
{
	xset r on
	echo stopping all collabkit processes...
	[ -e $ANNOTATE_PIDFILE ] && kill `cat $ANNOTATE_PIDFILE`
        rm -f $ANNOTATE_PIDFILE
       	[ -e $VNCSERV_PIDFILE ] && kill `cat $VNCSERV_PIDFILE`
	rm -f $VNCSERV_PIDFILE
	[ -e $VNCVIEW_PIDFILE ] && kill `cat $VNCVIEW_PIDFILE`
	rm -f $VNCVIEW_PIDFILE
}


runastrayicon()
{
   RUN=true

   while($RUN)
   do
        # off state
        start
        # on state
        zenity --info --text="CollabKit started." 
        zenity --notification --text "CollabKit is RUNNING. Click here to stop it." --window-icon=$ICON_STARTED
        zenity --question --text "Would you like to stop CollabKit? Answering NO quits."
        if [ $? -eq 1 ]; then
            RUN=false
            break
        fi
        stop
        # off state
	zenity --info --text="CollabKit stopped."
	zenity --notification --text "CollabKit is STOPPED. Click here to start it." --window-icon=$ICON_STOPPED
        zenity --question --text "Would you like to start CollabKit? Answering NO quits."
        if [ $? -eq 1 ]; then
            RUN=false
            break
        fi
   done
   
   stop
}



checkrandr()
{
   NR_CONNECTED=`xrandr | grep " connected" | wc -l`
   if [ $NR_CONNECTED -gt 1 ]; then
        DISPLAYS=`xrandr | grep " connected" | awk '{print $1}'`
        for i in $DISPLAYS; do 
           ARGS="FALSE $i $ARGS"
        done
   	ANS=`zenity --title "Choose display to share" --list --text "There are several displays connected.\nWhich ones to share with CollabKit?" \
   	--radiolist --column "Choose" --column "Display(s)" TRUE All $ARGS`
	if [ "$ANS" = "All" -o -z "$ANS" ]; then
	   return
	fi
	D=`echo $DISPLAYS | wc -w`
	for i in $DISPLAYS; do
	   D=$((D-1))
	   if [ "$ANS" = "$i" ]; then
	      break
	   fi
	done
   	MXVNC_OPTS="$MXVNC_OPTS -clip xinerama$D"
   fi
}



# go to working directory
cd `dirname $0`

# find icons
if [ -e /usr/share/icons/collabkit-started.svg ]; then
	ICON_STARTED=/usr/share/icons/collabkit-started.svg
else
	# use local icon
	ICON_STARTED=res/collabkit-started.svg
fi

if [ -e /usr/share/icons/collabkit-stopped.svg ]; then
	ICON_STOPPED=/usr/share/icons/collabkit-stopped.svg
else
	# use local icon
	ICON_STOPPED=res/collabkit-stopped.svg
fi



case "$1" in
  start)
	stop
	start
	;;
  stop)
	stop
	;;
  trayicon)
        checkrandr
	runastrayicon
	;;
  *)
	echo "Usage: $0 {start|stop|trayicon}" >&2
	exit 1
	;;
esac

exit 0
