#! /bin/sh
#
# very simple minded startup script for CollabKit
# created by Christian Beier <dontmind@freeshell.org>


# possible speedups:
# -noxdamage, -deferupdate 0, -input_skip <n>, -pointer_mode [1 or 4]
# -ncache <n>
# -nofb
# -threads
X11VNC_OPTS="-shared -forever -mdns -multiptr -pointer_mode 4 -threads -afteraccept setcursor_helper"
VIEWER_OPTS="-appshare -quality 7 -compresslevel 5"

    
#######################################################################

PATH=/usr/lib/collabkit:./bin:$PATH


ANNOTATE_PIDFILE=/tmp/CK-annotate.pid
VNCSERV_PIDFILE=/tmp/CK-vncserv.pid
VNCVIEW_PIDFILE=/tmp/CK-vncview.pid

#set -e

start()
{
        # first, start annotation app
	gromit-mpx &
	echo $! > $ANNOTATE_PIDFILE
        # then, the VNC server x11vnc
	x11vnc $X11VNC_OPTS &
	echo $! > $VNCSERV_PIDFILE
	# third, the vnc viewer to receive incoming windows
	vncviewer $VIEWER_OPTS &
	echo $! > $VNCVIEW_PIDFILE
}


stop()
{
	[ -e $ANNOTATE_PIDFILE ] && kill `cat $ANNOTATE_PIDFILE`
        rm -f $ANNOTATE_PIDFILE
       	[ -e $VNCSERV_PIDFILE ] && kill -2 `cat $VNCSERV_PIDFILE`
	rm -f $VNCSERV_PIDFILE
	[ -e $VNCVIEW_PIDFILE ] && kill `cat $VNCVIEW_PIDFILE`
	rm -f $VNCVIEW_PIDFILE
}


runastrayicon()
{
   RUN=true

   while($RUN)
   do
        # off state
        zenity --notification --text "CollabKit is STOPPED. Click here to start it." --window-icon=$ICON_STOPPED
        zenity --question --text "Would you like to start CollabKit? Answering NO quits."
        if [ $? -eq 1 ]; then
            RUN=false
            break
        fi
        start
        # on state
        zenity --info --text="CollabKit started." 
        zenity --notification --text "CollabKit is RUNNING. Click here to stop it." --window-icon=$ICON_STARTED
        zenity --question --text "Would you like to stop CollabKit? Answering NO quits."
        if [ $? -eq 1 ]; then
            RUN=false
            break
        fi
        stop
        # off state
	zenity --info --text="CollabKit stopped."
   done
   
   stop
}



# go to working directory
cd `dirname $0`

# find icons
if [ -e /usr/share/icons/collabkit-started.svg ]; then
	ICON_STARTED=/usr/share/icons/collabkit-started.svg
else
	# use local icon
	ICON_STARTED=res/collabkit-started.svg
fi

if [ -e /usr/share/icons/collabkit-stopped.svg ]; then
	ICON_STOPPED=/usr/share/icons/collabkit-stopped.svg
else
	# use local icon
	ICON_STOPPED=res/collabkit-stopped.svg
fi



case "$1" in
  start)
	stop
	start
	;;
  stop)
	stop
	;;
  trayicon)
	runastrayicon
	;;
  *)
	echo "Usage: $0 {start|stop|trayicon}" >&2
	exit 1
	;;
esac

exit 0
