#!/bin/sh

# This script, to be placed in /etc/network/if-up.d/,
# sets up a default multicast route. Needed when using
# wireless ad-hoc networking.

# Don't set multicast default route while bringing up
# the loopback device; it's not necessary until we bring up a real network
# device
[ "$IFACE" != "lo" ] || exit 0

route add -net 224.0.0.0 netmask 240.0.0.0 dev "$IFACE"